<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Terms of Service | {{ config('app.name') }}</title>
    <meta name="description" content="Terms of service for the GLC AI Platform - AI placement testing and 24/7 AI tutoring for Greats Language Center students.">
    <link rel="canonical" href="{{ url('/terms-of-service') }}">
    @vite('resources/css/app.css')
</head>
<body class="bg-slate-50 font-sans text-slate-900 antialiased">
    <div class="mx-auto max-w-3xl px-6 py-12">
        <a href="/" class="text-sm text-emerald-700 hover:underline">&larr; Back to GLC AI Platform</a>

        <article class="prose prose-slate mt-8">
            <h1>Terms of Service</h1>
            <p><strong>Greats Language Center (GLC) AI Platform</strong></p>
            <p><em>This is placeholder language pending review by GLC. It will be finalised before public launch.</em></p>

            <h2>1. The service</h2>
            <p>The GLC AI Platform provides AI-assisted English placement testing and a 24/7 AI tutor for students of Greats Language Center. Access is by invitation only: placement candidates receive a single-use access code, and student/staff accounts are created by GLC administrators. There is no public self-registration.</p>

            <h2>2. Acceptable use</h2>
            <ul>
                <li>Access codes and accounts are personal and must not be shared.</li>
                <li>Placement tests must be completed by the candidate alone, without assistance. Session events such as leaving the test tab are recorded.</li>
                <li>The AI tutor is a learning aid limited to GLC curriculum content. It does not complete graded homework for you, and misuse may be flagged to your teacher.</li>
            </ul>

            <h2>3. AI-generated content</h2>
            <p>Tutor replies and draft evaluations are generated by AI and may contain errors. Placement results are always reviewed and approved by GLC academic staff before being released. Placement outcomes are recommendations made by GLC, whose decision is final.</p>

            <h2>4. Minors</h2>
            <p>Students aged 12-17 may use the AI tutor only after a parent or guardian's consent has been recorded by GLC. The platform is not intended for children under 12 without GLC's explicit arrangement.</p>

            <h2>5. Liability</h2>
            <p>The platform is provided "as is" for educational purposes. To the maximum extent permitted by Malaysian law, GLC is not liable for indirect losses arising from use of the platform.</p>

            <h2>6. Contact</h2>
            <p>Questions about these terms should be directed to Greats Language Center administration, Kuala Lumpur, Malaysia.</p>
        </article>
    </div>
</body>
</html>
