import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import AuthLayout from '@/layouts/auth-layout';
import { Form, Head } from '@inertiajs/react';
import { LoaderCircle } from 'lucide-react';

export default function DisclaimerShow() {
    return (
        <AuthLayout
            title="Platform Disclaimer"
            description="Please review and accept before continuing"
        >
            <Head title="Platform Disclaimer" />
            <Form
                action="/disclaimer"
                method="post"
                className="flex flex-col gap-6"
            >
                {({ processing, errors }) => (
                    <>
                        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/50 dark:bg-amber-950/50 dark:text-amber-200">
                            <p className="mb-3 font-medium">
                                The GLC AI Platform provides AI-assisted
                                learning support, not certified assessment or
                                professional advice.
                            </p>
                            <ul className="list-inside list-disc space-y-1.5 text-xs">
                                <li>
                                    AI tutor replies and draft evaluations are
                                    generated by AI and may contain errors
                                </li>
                                <li>
                                    Placement results are always reviewed and
                                    approved by GLC academic staff before
                                    release
                                </li>
                                <li>
                                    The AI tutor is a learning aid limited to
                                    GLC curriculum content
                                </li>
                                <li>
                                    Contact your teacher or GLC administration
                                    for questions about your results
                                </li>
                            </ul>
                        </div>

                        <input type="hidden" name="accepted" value="1" />
                        <InputError message={errors.accepted} />

                        <Button
                            type="submit"
                            className="w-full"
                            disabled={processing}
                        >
                            {processing && (
                                <LoaderCircle className="h-4 w-4 animate-spin" />
                            )}
                            I understand and accept
                        </Button>
                    </>
                )}
            </Form>
        </AuthLayout>
    );
}
